### ISSUE TITLE
All Permissions are set enabled by default and can't disable

### ISSUE THREAD

**Issue by itsmeshibintmz** [PixysOS-Devices/device_nothing_Spacewar#1]
This is first time I'm seeing on a custom rom.
All permissions like location, contacts, call logs, microphone, camera are enabled by default for Google apps like Google, Chrome etc.. none can be disabled. It shows device requires this permission to operate. 
Attaching screenshots for reference.
Kindly look into it and resolve.

![Screenshot_20231012-084152](https://github.com/PixysOS-Devices/device_nothing_Spacewar/assets/52344717/6a4f6600-6250-45a2-be15-edb7fc2cb572)
![Screenshot_20231012-084201](https://github.com/PixysOS-Devices/device_nothing_Spacewar/assets/52344717/1f2088bb-d108-4c3a-a57e-7066cd2e2e18)

**Comment by aswin7469** [comment]
This was done as an attempt to fix issues with people flashing custom gms packages . Even tho we don't ship vanilla anymore this change got forward ported 

The commit in question is this : https://github.com/PixysOS/frameworks_base/commit/7eca9429eaa79bdc3c729e832a4150eaa937d6d6

This wouldn't change the default permissions but ye makes it unable to disable (eventually breaks some functionalities) . I will try to get rid of them in the next cycle or hopefully trim down this to just the important ones

**Comment by itsmeshibintmz** [comment]
Thanks for the quick response. Hope you can get rid of most of them in upcoming builds.

**Comment by itsmeshibintmz** [comment]
Thank you for fixing this. :)
